export const SRI_LANKA_ATTRACTIONS = [
  // --- COLOMBO ---
  {
    id: "colombo-gangaramaya",
    name: "Gangaramaya Temple & Seema Malaka",
    district: "Colombo",
    lat: 6.9167,
    lng: 79.8564,
    categories: ["Religious", "Historical", "Architecture"],
    ticketPrice: 500,
    openingHours: { open: 6.0, close: 22.0 },
    rating: 4.7,
    popularity: 92,
    estimatedVisitTime: 60,
    isActive: true,
    description: "An iconic Buddhist temple complex in Beira Lake featuring a museum, vintage cars, and brass statues."
  },
  {
    id: "colombo-lotus-tower",
    name: "Lotus Tower (Colombo)",
    district: "Colombo",
    lat: 6.9271,
    lng: 79.8578,
    categories: ["Architecture", "City", "Photography"],
    ticketPrice: 2000,
    openingHours: { open: 9.0, close: 22.0 },
    rating: 4.6,
    popularity: 90,
    estimatedVisitTime: 90,
    isActive: true,
    description: "South Asia's tallest self-supported tower offering 360-degree panoramic views of Colombo city and ocean."
  },
  {
    id: "colombo-galle-face",
    name: "Galle Face Green Promenade",
    district: "Colombo",
    lat: 6.9238,
    lng: 79.8458,
    categories: ["Beach", "Relaxation", "Food"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.5,
    popularity: 95,
    estimatedVisitTime: 60,
    isActive: true,
    description: "Vibrant oceanfront urban park famous for kite flying, sunset walks, and local street food stalls."
  },

  // --- GAMPAHA ---
  {
    id: "gampaha-botanical",
    name: "Henarathgoda Botanical Garden",
    district: "Gampaha",
    lat: 7.0931,
    lng: 79.9933,
    categories: ["Nature", "Relaxation", "Family"],
    ticketPrice: 300,
    openingHours: { open: 7.5, close: 17.5 },
    rating: 4.4,
    popularity: 78,
    estimatedVisitTime: 90,
    isActive: true,
    description: "Historic botanical gardens established in 1876 where Sri Lanka's first rubber trees were planted."
  },

  // --- KALUTARA ---
  {
    id: "kalutara-bodhiya",
    name: "Kalutara Bodhiya & Hollow Stupa",
    district: "Kalutara",
    lat: 6.5866,
    lng: 79.9592,
    categories: ["Religious", "Historical"],
    ticketPrice: 0,
    openingHours: { open: 5.0, close: 22.0 },
    rating: 4.8,
    popularity: 88,
    estimatedVisitTime: 45,
    isActive: true,
    description: "One of the world's few completely hollow Buddhist stupas, located at the mouth of Kalu Ganga river."
  },

  // --- KANDY ---
  {
    id: "kandy-tooth-temple",
    name: "Temple of the Sacred Tooth Relic",
    district: "Kandy",
    lat: 7.2936,
    lng: 80.6413,
    categories: ["Religious", "Historical"],
    ticketPrice: 2000,
    openingHours: { open: 5.5, close: 20.0 },
    rating: 4.9,
    popularity: 99,
    estimatedVisitTime: 90,
    isActive: true,
    description: "UNESCO World Heritage shrine housing the sacred tooth relic of Lord Buddha inside the royal palace complex."
  },
  {
    id: "kandy-peradeniya",
    name: "Peradeniya Royal Botanical Gardens",
    district: "Kandy",
    lat: 7.2681,
    lng: 80.5968,
    categories: ["Nature", "Family", "Photography"],
    ticketPrice: 3000,
    openingHours: { open: 7.5, close: 17.5 },
    rating: 4.8,
    popularity: 95,
    estimatedVisitTime: 120,
    isActive: true,
    description: "Sprawling 147-acre garden renowned for its orchid house, giant bamboo, and palm-lined avenues."
  },

  // --- MATALE & DAMBULLA ---
  {
    id: "matale-sigiriya",
    name: "Sigiriya Rock Fortress",
    district: "Matale",
    lat: 7.9570,
    lng: 80.7603,
    categories: ["Historical", "Adventure", "Photography"],
    ticketPrice: 10500,
    openingHours: { open: 7.0, close: 17.0 },
    rating: 4.9,
    popularity: 100,
    estimatedVisitTime: 180,
    isActive: true,
    description: "Majestic 5th-century ancient palace fortress built atop a 200-meter rock with world-renowned frescoes."
  },
  {
    id: "dambulla-cave-temple",
    name: "Dambulla Royal Cave Temple",
    district: "Dambulla",
    lat: 7.8566,
    lng: 80.6485,
    categories: ["Religious", "Historical"],
    ticketPrice: 2000,
    openingHours: { open: 7.0, close: 19.0 },
    rating: 4.8,
    popularity: 94,
    estimatedVisitTime: 90,
    isActive: true,
    description: "Best preserved cave temple complex in Sri Lanka containing 153 Buddha statues and intricate wall murals."
  },
  {
    id: "matale-nalanda",
    name: "Nalanda Gedige (Geographical Center)",
    district: "Matale",
    lat: 7.6710,
    lng: 80.6475,
    categories: ["Historical", "Architecture"],
    ticketPrice: 500,
    openingHours: { open: 7.0, close: 18.0 },
    rating: 4.6,
    popularity: 82,
    estimatedVisitTime: 45,
    isActive: true,
    description: "Unique stone temple blending Hindu Tantric and Buddhist architecture at the geographical midpoint of Sri Lanka."
  },

  // --- NUWARA ELIYA ---
  {
    id: "nuwaraeliya-gregory",
    name: "Gregory Lake & Park",
    district: "Nuwara Eliya",
    lat: 6.9534,
    lng: 80.7820,
    categories: ["Nature", "Relaxation", "Family"],
    ticketPrice: 200,
    openingHours: { open: 6.0, close: 18.0 },
    rating: 4.6,
    popularity: 91,
    estimatedVisitTime: 90,
    isActive: true,
    description: "Picturesque highland lake offering boat rides, horseback riding, and crisp mountain air."
  },
  {
    id: "nuwaraeliya-horton",
    name: "Horton Plains & World's End",
    district: "Nuwara Eliya",
    lat: 6.8026,
    lng: 80.8038,
    categories: ["Nature", "Adventure", "Hiking"],
    ticketPrice: 6500,
    openingHours: { open: 6.0, close: 16.0 },
    rating: 4.9,
    popularity: 96,
    estimatedVisitTime: 240,
    isActive: true,
    description: "High altitude cloud forest plateau leading to a sheer 880-meter vertical cliff drop at World's End."
  },

  // --- GALLE ---
  {
    id: "galle-dutch-fort",
    name: "Galle Dutch Fort & Lighthouse",
    district: "Galle",
    lat: 6.0267,
    lng: 80.2170,
    categories: ["Historical", "Beach", "Photography"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.8,
    popularity: 98,
    estimatedVisitTime: 120,
    isActive: true,
    description: "UNESCO living heritage fort with 17th-century ramparts, cobblestone alleys, cafes, and ocean views."
  },
  {
    id: "galle-unawatuna",
    name: "Unawatuna & Jungle Beach",
    district: "Galle",
    lat: 6.0097,
    lng: 80.2486,
    categories: ["Beach", "Nature", "Relaxation"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.7,
    popularity: 92,
    estimatedVisitTime: 120,
    isActive: true,
    description: "Golden horseshoe bay famous for calm turquoise swimming waters, coral reefs, and beach lounges."
  },

  // --- MATARA ---
  {
    id: "matara-mirissa-hill",
    name: "Mirissa Coconut Tree Hill",
    district: "Matara",
    lat: 5.9450,
    lng: 80.4610,
    categories: ["Nature", "Beach", "Photography"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.8,
    popularity: 95,
    estimatedVisitTime: 60,
    isActive: true,
    description: "Iconic red-clay cliff dome filled with tall palm trees jutting directly out into the Indian Ocean."
  },

  // --- HAMBANTOTA ---
  {
    id: "hambantota-yala",
    name: "Yala National Park (Jeep Safari)",
    district: "Hambantota",
    lat: 6.3718,
    lng: 81.5168,
    categories: ["Wildlife", "Adventure", "Nature"],
    ticketPrice: 7500,
    openingHours: { open: 6.0, close: 18.0 },
    rating: 4.9,
    popularity: 99,
    estimatedVisitTime: 240,
    isActive: true,
    description: "Sri Lanka's premier wildlife sanctuary possessing the world's highest density of wild leopards."
  },

  // --- ANURADHAPURA ---
  {
    id: "anuradhapura-ruwanwelisaya",
    name: "Ruwanwelisaya Sacred Great Stupa",
    district: "Anuradhapura",
    lat: 8.3500,
    lng: 80.3962,
    categories: ["Religious", "Historical"],
    ticketPrice: 1000,
    openingHours: { open: 6.0, close: 21.0 },
    rating: 4.9,
    popularity: 97,
    estimatedVisitTime: 75,
    isActive: true,
    description: "Monumental 140-meter white stupa built by King Dutugemunu in 140 BC, encircled by an elephant wall."
  },
  {
    id: "anuradhapura-mihintale",
    name: "Mihintale Sacred Mountain Peak",
    district: "Anuradhapura",
    lat: 8.3524,
    lng: 80.5042,
    categories: ["Religious", "Historical", "Hiking"],
    ticketPrice: 1000,
    openingHours: { open: 6.0, close: 19.0 },
    rating: 4.8,
    popularity: 90,
    estimatedVisitTime: 90,
    isActive: true,
    description: "Cradle of Sri Lankan Buddhism where Arahat Mahinda met King Devanampiyatissa in 247 BC."
  },

  // --- POLONNARUWA ---
  {
    id: "polonnaruwa-galviharaya",
    name: "Gal Viharaya Rock Sculptures",
    district: "Polonnaruwa",
    lat: 7.9654,
    lng: 81.0048,
    categories: ["Historical", "Religious", "Architecture"],
    ticketPrice: 1000,
    openingHours: { open: 7.0, close: 18.0 },
    rating: 4.9,
    popularity: 94,
    estimatedVisitTime: 75,
    isActive: true,
    description: "Masterpiece of Sinhalese granite carving featuring colossal standing, seated, and reclining Buddha statues."
  },

  // --- JAFFNA ---
  {
    id: "jaffna-nallur-kovil",
    name: "Nallur Kandaswamy Kovil",
    district: "Jaffna",
    lat: 9.6746,
    lng: 80.0298,
    categories: ["Religious", "Historical", "Architecture"],
    ticketPrice: 0,
    openingHours: { open: 5.0, close: 21.0 },
    rating: 4.9,
    popularity: 98,
    estimatedVisitTime: 90,
    isActive: true,
    description: "The grand spiritual heart of Jaffna Peninsula, famed for golden gopuram towers and sacred festivals."
  },
  {
    id: "jaffna-dutch-fort",
    name: "Jaffna Dutch Fort",
    district: "Jaffna",
    lat: 9.6616,
    lng: 80.0094,
    categories: ["Historical", "Photography"],
    ticketPrice: 0,
    openingHours: { open: 8.0, close: 18.0 },
    rating: 4.6,
    popularity: 91,
    estimatedVisitTime: 75,
    isActive: true,
    description: "Large pentagonal coastal fort constructed by the Portuguese in 1618 and fortified by the Dutch."
  },
  {
    id: "jaffna-keerimalai",
    name: "Keerimalai Sacred Water Springs",
    district: "Jaffna",
    lat: 9.8142,
    lng: 80.0135,
    categories: ["Nature", "Religious", "Beach"],
    ticketPrice: 200,
    openingHours: { open: 6.0, close: 18.0 },
    rating: 4.5,
    popularity: 85,
    estimatedVisitTime: 60,
    isActive: true,
    description: "Natural mineral spring pool situated right on the northern sea edge believed to have curative waters."
  },

  // --- KILINOCHCHI & MANNAR & VAVUNIYA & MULLAITIVU ---
  {
    id: "kilinochchi-elephantpass",
    name: "Elephant Pass Highway War Memorial",
    district: "Kilinochchi",
    lat: 9.5312,
    lng: 80.4071,
    categories: ["Historical"],
    ticketPrice: 0,
    openingHours: { open: 6.0, close: 18.0 },
    rating: 4.5,
    popularity: 82,
    estimatedVisitTime: 45,
    isActive: true,
    description: "Strategic causeway gateway connecting the Jaffna peninsula to mainland Sri Lanka."
  },
  {
    id: "mannar-baobab",
    name: "Mannar Baobab Tree & Fort",
    district: "Mannar",
    lat: 8.9772,
    lng: 79.9042,
    categories: ["Nature", "Historical"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.5,
    popularity: 78,
    estimatedVisitTime: 45,
    isActive: true,
    description: "Ancient 700-year-old African baobab tree planted by Arab traders on Mannar Island."
  },
  {
    id: "vavuniya-museum",
    name: "Vavuniya Archaeological Museum",
    district: "Vavuniya",
    lat: 8.7514,
    lng: 80.4971,
    categories: ["Historical"],
    ticketPrice: 200,
    openingHours: { open: 8.5, close: 16.5 },
    rating: 4.3,
    popularity: 70,
    estimatedVisitTime: 45,
    isActive: true,
    description: "Regional museum housing ancient Buddhist and Hindu stone statues excavated from Northern Province."
  },
  {
    id: "mullaitivu-beach",
    name: "Maritimepattu Beach",
    district: "Mullaitivu",
    lat: 9.2671,
    lng: 80.8142,
    categories: ["Beach", "Nature"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.4,
    popularity: 72,
    estimatedVisitTime: 60,
    isActive: true,
    description: "Pristine, untouched east coast beach stretch with tranquil waters."
  },

  // --- TRINCOMALEE ---
  {
    id: "trinco-koneswaram",
    name: "Koneswaram Temple & Swami Rock",
    district: "Trincomalee",
    lat: 8.5775,
    lng: 81.2404,
    categories: ["Religious", "Historical", "Nature"],
    ticketPrice: 0,
    openingHours: { open: 6.0, close: 19.0 },
    rating: 4.9,
    popularity: 96,
    estimatedVisitTime: 90,
    isActive: true,
    description: "Classical Hindu cliffside temple perched high over the deep blue waters of Gokarna Bay."
  },
  {
    id: "trinco-nilaveli",
    name: "Nilaveli Beach & Pigeon Island",
    district: "Trincomalee",
    lat: 8.7064,
    lng: 81.2062,
    categories: ["Beach", "Wildlife", "Nature"],
    ticketPrice: 2500,
    openingHours: { open: 7.0, close: 17.0 },
    rating: 4.8,
    popularity: 94,
    estimatedVisitTime: 180,
    isActive: true,
    description: "White sand beach and marine national park famous for snorkeling with live coral reef sharks and turtles."
  },

  // --- BATTICALOA & AMPARA ---
  {
    id: "batti-fort",
    name: "Batticaloa Dutch Fort & Lagoon",
    district: "Batticaloa",
    lat: 7.7170,
    lng: 81.7000,
    categories: ["Historical", "Nature"],
    ticketPrice: 0,
    openingHours: { open: 8.0, close: 17.0 },
    rating: 4.5,
    popularity: 82,
    estimatedVisitTime: 60,
    isActive: true,
    description: "Charming 1628 coastal fort surrounded by the quiet waters of Batticaloa Lagoon."
  },
  {
    id: "batti-pasikudah",
    name: "Pasikudah Coral Bay",
    district: "Batticaloa",
    lat: 7.9230,
    lng: 81.5640,
    categories: ["Beach", "Relaxation"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.8,
    popularity: 93,
    estimatedVisitTime: 120,
    isActive: true,
    description: "Shallow curved bay with clear warm waters where you can walk out 150 meters into the sea."
  },
  {
    id: "ampara-arugambay",
    name: "Arugam Bay Surfing Beach",
    district: "Ampara",
    lat: 6.8417,
    lng: 81.8358,
    categories: ["Beach", "Adventure", "Food"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.9,
    popularity: 97,
    estimatedVisitTime: 180,
    isActive: true,
    description: "World famous right-point break surf destination with a laid-back international beach vibe."
  },

  // --- KURUNEGALA & PUTTALAM ---
  {
    id: "kurunegala-ethagala",
    name: "Ethagala Giant Buddha Rock",
    district: "Kurunegala",
    lat: 7.4870,
    lng: 80.3653,
    categories: ["Historical", "Religious", "Photography"],
    ticketPrice: 0,
    openingHours: { open: 6.0, close: 18.0 },
    rating: 4.5,
    popularity: 84,
    estimatedVisitTime: 90,
    isActive: true,
    description: "Huge 88-foot white Buddha statue overlooking Kurunegala town from atop Elephant Rock."
  },
  {
    id: "puttalam-wilpattu",
    name: "Wilpattu National Park Entry",
    district: "Puttalam",
    lat: 8.4550,
    lng: 80.0400,
    categories: ["Wildlife", "Nature", "Adventure"],
    ticketPrice: 7000,
    openingHours: { open: 6.0, close: 18.0 },
    rating: 4.8,
    popularity: 92,
    estimatedVisitTime: 240,
    isActive: true,
    description: "Sri Lanka's largest national park famous for natural rainwater lakes ('Villus'), leopards, and sloth bears."
  },

  // --- BADULLA & MONARAGALA ---
  {
    id: "badulla-ninearch",
    name: "Nine Arch Bridge (Ella)",
    district: "Badulla",
    lat: 6.8768,
    lng: 81.0608,
    categories: ["Historical", "Nature", "Photography"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.9,
    popularity: 99,
    estimatedVisitTime: 90,
    isActive: true,
    description: "Colonial-era railway viaduct bridge tucked into lush green tea country."
  },
  {
    id: "badulla-ravana",
    name: "Ravana Waterfalls",
    district: "Badulla",
    lat: 6.8378,
    lng: 81.0545,
    categories: ["Waterfall", "Nature"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.7,
    popularity: 94,
    estimatedVisitTime: 45,
    isActive: true,
    description: "Spectacular 25-meter cascading waterfall right along the main Ella-Wellawaya highway road."
  },
  {
    id: "monaragala-buduruwagala",
    name: "Buduruwagala Rock Sculptures (Wellawaya)",
    district: "Monaragala",
    lat: 6.6833,
    lng: 81.0833,
    categories: ["Historical", "Religious"],
    ticketPrice: 500,
    openingHours: { open: 7.0, close: 18.0 },
    rating: 4.6,
    popularity: 83,
    estimatedVisitTime: 60,
    isActive: true,
    description: "Seven 10th-century Mahayana Buddhist figures carved into a secluded cliff face inside dry forest."
  },

  // --- RATNAPURA & KEGALLE ---
  {
    id: "ratnapura-adamsspeak",
    name: "Adam's Peak (Sri Pada Trailhead)",
    district: "Ratnapura",
    lat: 6.8096,
    lng: 80.4994,
    categories: ["Religious", "Hiking", "Nature"],
    ticketPrice: 0,
    openingHours: { open: 0, close: 24 },
    rating: 4.9,
    popularity: 98,
    estimatedVisitTime: 360,
    isActive: true,
    description: "Sacred 2,243-meter mountain pilgrimage peak famous for the sacred footprint and sunrise shadow."
  },
  {
    id: "kegalle-pinnawala",
    name: "Pinnawala Elephant Orphanage",
    district: "Kegalle",
    lat: 7.3014,
    lng: 80.3871,
    categories: ["Wildlife", "Family"],
    ticketPrice: 3000,
    openingHours: { open: 8.5, close: 17.5 },
    rating: 4.6,
    popularity: 93,
    estimatedVisitTime: 120,
    isActive: true,
    description: "Captive breeding and conservation park where herds of Asian elephants bathe in the Ma Oya river."
  }
];
