export const attractions = [
  {
    id: "sigiriya",
    name: "Sigiriya Rock Fortress",
    category: "heritage",
    rating: 4.9,
    time: "3–4 hours",
    image: "https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?auto=format&fit=crop&w=800&q=80",
    description: "An ancient rock fortress and palace ruins of unmatched beauty, Sigiriya (Lion Rock) is a UNESCO World Heritage site featuring breathtaking frescoes, the mirror wall, and terraced gardens climbing 180 meters high. Built by King Kashyapa, it stands as a testament to early urban planning and military architecture.",
    district: "Matale",
    bestSeason: "January to April",
    vibe: "Ancient Wonders & Majesty",
    activities: "Climbing, History exploration, Photography",
    access: "Staircase climb up to the summit",
    dressCode: "Comfortable activewear & sunhat",
    googleMapsUrl: "https://maps.google.com/?q=Sigiriya+Rock+Fortress"
  },
  {
    id: "galle-fort",
    name: "Galle Dutch Fort",
    category: "heritage",
    rating: 4.7,
    time: "2–3 hours",
    image: "/galle.jpg",
    description: "A historical coastal fortification built by the Portuguese and extensively fortified by the Dutch. Galle Fort features a charming blend of European colonial architecture and South Asian traditions, containing cozy boutiques, cafes, and scenic ramparts overlooking the Indian Ocean.",
    district: "Galle",
    bestSeason: "November to April",
    vibe: "Colonial Charm & Sunset Walks",
    activities: "Rampart walks, Boutique shopping, Coffee tasting",
    access: "Easy vehicle access & walking paths",
    dressCode: "Casual beach/resort wear",
    googleMapsUrl: "https://maps.google.com/?q=Galle+Fort"
  },
  {
    id: "kandy-temple",
    name: "Temple of the Tooth",
    category: "heritage",
    rating: 4.8,
    time: "1–2 hours",
    image: "/kandy.jpg",
    description: "Located in the royal palace complex of the former Kingdom of Kandy, this golden-roofed Buddhist temple houses the sacred tooth relic of Lord Buddha. It is one of the most venerated shrines in the Buddhist world and acts as the spiritual heart of Kandy.",
    district: "Kandy",
    bestSeason: "Year-Round",
    vibe: "Sacred Peace & Devotion",
    activities: "Traditional rituals (Tewava) observation, Prayer, Museum tours",
    access: "Footpaths through palace gates",
    dressCode: "Modest attire (shoulders and knees covered)",
    googleMapsUrl: "https://maps.google.com/?q=Temple+of+the+Tooth+Kandy"
  },
  {
    id: "yala-park",
    name: "Yala National Park",
    category: "wildlife",
    rating: 4.7,
    time: "Full day",
    image: "/lagoon.jpeg",
    description: "Sri Lanka's most popular national park boasts one of the highest leopard densities in the world. Visitors can embark on safari drives to witness elephants, sloth bears, spotted deer, peacocks, and crocodiles roaming freely across coastal lagoons and scrub forests.",
    district: "Hambantota",
    bestSeason: "February to June (Dry)",
    vibe: "Wild Wilderness & High Adventure",
    activities: "4x4 Safari drives, Birdwatching, Campfire stays",
    access: "4x4 Jeep only",
    dressCode: "Durable safari clothing (earthy tones recommended)",
    googleMapsUrl: "https://maps.google.com/?q=Yala+National+Park"
  },
  {
    id: "mirissa-beach",
    name: "Mirissa Beach",
    category: "beach",
    rating: 4.6,
    time: "Half day",
    image: "/beach.jpg",
    description: "Famous for whale watching excursions, golden crescent sands, and lively beachside seafood restaurants. Mirissa features popular viewpoints like Coconut Tree Hill and offers excellent waves for surfing and safe swimming bays.",
    district: "Matara",
    bestSeason: "November to April",
    vibe: "Vibrant, Social & Coastal Chill",
    activities: "Whale watching, Surfing, Snorkeling, Sunbathing",
    access: "Direct access off Matara Road",
    dressCode: "Beachwear, sunglasses & sandals",
    googleMapsUrl: "https://maps.google.com/?q=Mirissa+Beach"
  },
  {
    id: "nine-arch",
    name: "Nine Arch Bridge",
    category: "heritage",
    rating: 4.8,
    time: "1–2 hours",
    image: "https://images.unsplash.com/photo-1545284929-de966378e945?auto=format&fit=crop&w=800&q=80",
    description: "A monumental railway bridge in Ella constructed entirely from brick, rock, and cement without a single piece of steel. Nestled amidst lush green tea gardens and forest groves, it offers iconic photo opportunities when local trains pass over.",
    district: "Badulla",
    bestSeason: "January to May",
    vibe: "Scenic Countryside Nostalgia",
    activities: "Hiking, Train watching, Photography",
    access: "Tuk-tuk ride or jungle footpath walk",
    dressCode: "Comfortable casual wear",
    googleMapsUrl: "https://maps.google.com/?q=Nine+Arch+Bridge+Ella"
  },
  {
    id: "ella-hike",
    name: "Ella Rock Hike",
    category: "mountain",
    rating: 4.6,
    time: "3–4 hours",
    image: "/sunset.jpeg",
    description: "A rewarding hill-country trek that guides hikers past active railway tracks, local vegetable farms, and pine forests to a high cliff summit. Offers dramatic panoramic vistas of the Ella Gap and valleys below.",
    district: "Badulla",
    bestSeason: "January to May & July to August",
    vibe: "Adventure & Alpine Mist",
    activities: "Mountain trekking, Nature walks, Landscape photography",
    access: "Challenging climb requiring proper trail routes",
    dressCode: "Sturdy hiking shoes & layers",
    googleMapsUrl: "https://maps.google.com/?q=Ella+Rock+Trailhead"
  },
  {
    id: "diyaluma-falls",
    name: "Diyaluma Falls",
    category: "waterfall",
    rating: 4.7,
    time: "2–3 hours",
    image: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=800&q=80",
    description: "At 220 meters, Diyaluma is the second-highest waterfall in Sri Lanka. The upper falls feature a series of natural infinity pools overlooking the high mountain valleys, ideal for a refreshing freshwater swim.",
    district: "Badulla",
    bestSeason: "June to September & December to January",
    vibe: "Roaring Water & Infinity Pools",
    activities: "Swimming, Cliff pools bathing, Mountain trekking",
    access: "Hiking trek from Koslanda village",
    dressCode: "Swimwear & dry clothing change",
    googleMapsUrl: "https://maps.google.com/?q=Diyaluma+Falls"
  },
  {
    id: "galle-face-mall",
    name: "One Galle Face Mall",
    category: "city",
    rating: 4.5,
    time: "2–3 hours",
    image: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=800&q=80",
    description: "Sri Lanka's premier international shopping mall featuring multi-story retail stores, top global brands, a state-of-the-art cinema complex, and a massive international dining food court located right next to the Galle Face Green promenade.",
    district: "Colombo",
    bestSeason: "Year-Round",
    vibe: "Bustling Urban Commerce",
    activities: "Shopping, Fine dining, IMAX movies, Family entertainment",
    access: "Easy vehicle drop-off",
    dressCode: "Smart casual",
    googleMapsUrl: "https://maps.google.com/?q=One+Galle+Face+Mall+Colombo"
  },
  {
    id: "udawalawe",
    name: "Udawalawe National Park",
    category: "wildlife",
    rating: 4.8,
    time: "Half day",
    image: "https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=800&q=80",
    description: "Famous for its large population of Sri Lankan elephants, this national park surrounds a massive scenic reservoir. It offers highly consistent elephant sightings in open grass terrain, alongside birds, deer, and jackals.",
    district: "Ratnapura",
    bestSeason: "May to September",
    vibe: "Elephants & Lake Vistas",
    activities: "Open Jeep safari, Elephant transit home visit",
    access: "4x4 Jeep ride",
    dressCode: "Lightweight clothes & sun hat",
    googleMapsUrl: "https://maps.google.com/?q=Udawalawe+National+Park"
  },
  {
    id: "horton-plains",
    name: "Horton Plains National Park",
    category: "mountain",
    rating: 4.7,
    time: "Full day",
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
    description: "A cold, mist-shrouded plateau of montane grasslands and cloud forests home to endemic Sambhur deer. The loop walk leads to the famous World's End cliff, dropping precipitously nearly 880 meters down.",
    district: "Nuwara Eliya",
    bestSeason: "January to March",
    vibe: "Cold Plains & Sheer Cliffs",
    activities: "Trekking, Birdwatching, Baker's Falls photography",
    access: "Flat circular walking loop (9km)",
    dressCode: "Warm jacket & sneakers (chilly mornings)",
    googleMapsUrl: "https://maps.google.com/?q=Horton+Plains+World's+End"
  },
  {
    id: "bambarakanda",
    name: "Bambarakanda Falls",
    category: "waterfall",
    rating: 4.6,
    time: "2 hours",
    image: "https://images.unsplash.com/photo-1434394354979-a235cd36269d?auto=format&fit=crop&w=800&q=80",
    description: "Plunging from a height of 263 meters through a dense pine forest, Bambarakanda is the highest waterfall in Sri Lanka. Surrounded by deep valleys and green hills, it offers a dramatic visual spectacle during monsoonal seasons.",
    district: "Badulla",
    bestSeason: "March to May & September to November",
    vibe: "Tallest Cascade & Pine Valleys",
    activities: "Forest walks, Waterfall photography, Trekking",
    access: "Walk from the Kalupahana-Ohiya road",
    dressCode: "Comfortable shoes & hiking gear",
    googleMapsUrl: "https://maps.google.com/?q=Bambarakanda+Falls"
  },
  {
    id: "pigeon-island",
    name: "Pigeon Island Marine Park",
    category: "wildlife",
    rating: 4.7,
    time: "Half day",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
    description: "One of the country's two marine national parks, situated off the coast of Nilaveli. It contains beautifully preserved shallow coral reefs that host sea turtles, blacktip reef sharks, and hundreds of vibrant tropical fish species.",
    district: "Trincomalee",
    bestSeason: "May to October",
    vibe: "Coral Reefs & Marine Life",
    activities: "Snorkeling, Scuba diving, Boat tours",
    access: "Short speedboat ride from Nilaveli Beach",
    dressCode: "Swimwear, rash guard & snorkel gear",
    googleMapsUrl: "https://maps.google.com/?q=Pigeon+Island+National+Park"
  },
  {
    id: "unawatuna",
    name: "Unawatuna Beach",
    category: "beach",
    rating: 4.5,
    time: "Half day",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    description: "A popular, semi-circular bay beach lined with swaying palm trees, trendy cafes, and beach clubs. Unawatuna's calm waters are protected by a reef, making it highly suitable for swimming and family holidays.",
    district: "Galle",
    bestSeason: "November to April",
    vibe: "Social, Lively & Tourist Hub",
    activities: "Swimming, Jet skiing, Seafood dining, Nightlife",
    access: "Direct access via Unawatuna main street",
    dressCode: "Casual beachwear",
    googleMapsUrl: "https://maps.google.com/?q=Unawatuna+Beach"
  },
  {
    id: "dambulla-cave",
    name: "Dambulla Cave Temple",
    category: "heritage",
    rating: 4.8,
    time: "2 hours",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    description: "A vast rock cave complex that has been a sacred place of worship since the 1st century BC. Houses five main caves decorated with intricate Buddhist murals and over 150 life-sized statues of Lord Buddha, kings, and deities.",
    district: "Matale",
    bestSeason: "Year-Round",
    vibe: "Sacred Antiquity & Cave Murals",
    activities: "Historical sightseeing, Devotion, Photography",
    access: "Moderate rock stair climb from the ground temple",
    dressCode: "Strict modest dress (knees and shoulders covered)",
    googleMapsUrl: "https://maps.google.com/?q=Dambulla+Cave+Temple"
  },
  {
    id: "adams-peak",
    name: "Adam's Peak (Sri Pada)",
    category: "mountain",
    rating: 4.9,
    time: "6–8 hours",
    image: "https://images.unsplash.com/photo-1545284929-de966378e945?auto=format&fit=crop&w=800&q=80",
    description: "A sacred mountain peak revered across multiple religions. Climbers ascend over 5,000 stone steps under the stars to witness the holy footprint at the summit and catch a legendary sunrise casting the mountain's triangular shadow.",
    district: "Ratnapura",
    bestSeason: "December to April (Pilgrimage season)",
    vibe: "Sacred Pilgrimage & Physical Challenge",
    activities: "Night trekking, Sunrise viewing, Religious worship",
    access: "Strenuous uphill stairs trek",
    dressCode: "Comfortable layers & modest summit wear",
    googleMapsUrl: "https://maps.google.com/?q=Adam's+Peak"
  },
  {
    id: "ravana-falls",
    name: "Ravana Falls",
    category: "waterfall",
    rating: 4.5,
    time: "1 hour",
    image: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=800&q=80",
    description: "One of Sri Lanka's widest waterfalls, cascading down a series of rocky tiers right beside the main highway in Ella. Named after the legendary king Ravana from the Ramayana, who is said to have hidden inside caves nearby.",
    district: "Badulla",
    bestSeason: "June to September",
    vibe: "Roadside Majesty & Mythology",
    activities: "Scenic viewpoint, Photography, Local snacks tasting",
    access: "Directly on the Ella-Wellawaya roadside",
    dressCode: "Casual comfortable clothing",
    googleMapsUrl: "https://maps.google.com/?q=Ravana+Falls"
  },
  {
    id: "kcc-mall",
    name: "Kandy City Centre",
    category: "city",
    rating: 4.4,
    time: "2 hours",
    image: "/kandy.jpg",
    description: "The commercial heart of the hill capital. This modern, multi-story shopping complex features brand outlets, electronic stores, dining options, and a supermarket, built with a design that respects Kandy's traditional heritage.",
    district: "Kandy",
    bestSeason: "Year-Round",
    vibe: "Urban Hill Country Shopping",
    activities: "Shopping, Cafes, Grocery runs, Souvenir shopping",
    access: "Vehicle drop-off & parking levels",
    dressCode: "Casual wear",
    googleMapsUrl: "https://maps.google.com/?q=Kandy+City+Centre"
  },
  {
    id: "sinharaja",
    name: "Sinharaja Forest Reserve",
    category: "wildlife",
    rating: 4.8,
    time: "Full day",
    image: "https://images.unsplash.com/photo-1511497584788-8767611136f6?auto=format&fit=crop&w=800&q=80",
    description: "A virgin tropical rainforest and UNESCO Biosphere Reserve. Extremely rich in biodiversity, it is home to over 60% of Sri Lanka's endemic trees and high numbers of endemic bird, butterfly, and amphibian species.",
    district: "Ratnapura",
    bestSeason: "January to March & August to September",
    vibe: "Primeval Jungle & Biological Sanctuary",
    activities: "Guided jungle hiking, Bird watching, Stream walks",
    access: "Dirt trails (requires registered forest guides)",
    dressCode: "Earthy tones, long pants & leech socks",
    googleMapsUrl: "https://maps.google.com/?q=Sinharaja+Forest+Reserve"
  },
  {
    id: "nilaveli",
    name: "Nilaveli Beach",
    category: "beach",
    rating: 4.7,
    time: "Half day",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    description: "A wide, white-sand beach with crystal clear waters in the east of Sri Lanka. Perfect for calm swims, relaxing beach runs, and setting off on boat trips to the nearby Pigeon Island Marine Reserve.",
    district: "Trincomalee",
    bestSeason: "May to October",
    vibe: "Tranquil Sands & Clear Water",
    activities: "Snorkeling boat departures, Swimming, Relaxation",
    access: "Direct village roads from Trincomalee town",
    dressCode: "Beachwear & sunglasses",
    googleMapsUrl: "https://maps.google.com/?q=Nilaveli+Beach"
  },
  {
    id: "anuradhapura",
    name: "Anuradhapura Sacred City",
    category: "heritage",
    rating: 4.8,
    time: "Full day",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    description: "The first ancient capital of Sri Lanka, established in the 4th century BC. This extensive UNESCO site is famous for its colossal brick stupas, ruins of monasteries, sacred ponds, and the Jaya Sri Maha Bodhi tree.",
    district: "Anuradhapura",
    bestSeason: "June to September & December to February",
    vibe: "Ancient Monastic Peace",
    activities: "Archaeology tours, Spiritual visits, Cycling",
    access: "Flat paths suitable for bicycles or cars",
    dressCode: "Strict white or light-colored modest wear",
    googleMapsUrl: "https://maps.google.com/?q=Anuradhapura+Sacred+City"
  },
  {
    id: "devon-falls",
    name: "Devon Falls",
    category: "waterfall",
    rating: 4.6,
    time: "1 hour",
    image: "https://images.unsplash.com/photo-1434394354979-a235cd36269d?auto=format&fit=crop&w=800&q=80",
    description: "Known as the 'Veil of the Valley', Devon Falls plunges 97 meters down rocky slopes surrounded by pristine green tea estates. It is visible from the main roadside park in Talawakelle.",
    district: "Nuwara Eliya",
    bestSeason: "June to September & November to January",
    vibe: "Tea Estates & Misty Falls",
    activities: "Tea estate walks, Roadside viewpoint photography",
    access: "Easy roadside view platform access",
    dressCode: "Casual daily clothes",
    googleMapsUrl: "https://maps.google.com/?q=Devon+Falls+View+Point"
  },
  {
    id: "pettah-market",
    name: "Pettah Floating Market",
    category: "city",
    rating: 4.3,
    time: "2 hours",
    image: "https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?auto=format&fit=crop&w=800&q=80",
    description: "A modernized floating shopping zone situated on the Beira Lake canal. Offers a collection of stalls selling apparel, accessories, and local snacks in a relaxed waterfront boardwalk environment.",
    district: "Colombo",
    bestSeason: "Year-Round",
    vibe: "Urban Canals & Waterfront Walkways",
    activities: "Evening walking, Snacking, Souvenir shopping",
    access: "Easy pedestrian access from Bastian Mawatha",
    dressCode: "Casual comfortable attire",
    googleMapsUrl: "https://maps.google.com/?q=Pettah+Floating+Market"
  },
  {
    id: "pidurangala",
    name: "Pidurangala Rock",
    category: "mountain",
    rating: 4.8,
    time: "2 hours",
    image: "https://images.unsplash.com/photo-1545284929-de966378e945?auto=format&fit=crop&w=800&q=80",
    description: "Located opposite Sigiriya Lion Rock, Pidurangala is a popular alternative hike offering the absolute best panoramic sunrise view of Sigiriya Rock itself. Features ancient caves and reclining Buddha statue along the trail.",
    district: "Matale",
    bestSeason: "January to May",
    vibe: "Sunrise Vistas & Adventure climbing",
    activities: "Rock scrambling, Sunrise hiking, Cave temple viewing",
    access: "Moderate rock climb (includes boulder scrambling)",
    dressCode: "Sturdy grip shoes, shoulders/knees covered for temple entrance",
    googleMapsUrl: "https://maps.google.com/?q=Pidurangala+Rock"
  }
];
